language: C99
before-install:
    - wget "https://dev.mysql.com/get/mysql-apt-config_0.8.15-1_all.deb"
    - sudo apt-get update -q
    - sudo apt-get install ./mysql-apt-config_0.8.15-1_all.deb
    - sudo apt-get install libmysqlclient-dev -y
compiler:
    - gcc
script:
    - cd client/src
    - make -d
